### ISSUE TITLE
Do this code surely runs with python2.7?

### ISSUE THREAD

**Issue by tyluann** [bharat-b7/MultiGarmentNetwork#36]
With python2.7, I run into syntax errors like:

Traceback (most recent call last):
  File "/home/tyluan/Workspace/py_projects/MultiGarmentNetwork/visualize_scan.py", line 9, in <module>
    from psbody.mesh import Mesh, MeshViewer
  File "/media/sdf/tyluan/Workspace/py_projects/MultiGarmentNetwork/psbody/mesh/__init__.py", line 10, in <module>
    from .meshviewer import MeshViewer, MeshViewers
  File "/media/sdf/tyluan/Workspace/py_projects/MultiGarmentNetwork/psbody/mesh/meshviewer.py", line 112
    print(e, file=sys.stderr)
                 ^
SyntaxError: invalid syntax

It is a typical error when using python2 for python3 code. So I tried python3.7 and I run into this:

/home/tyluan/Workspace/py_projects/venv_py3_tf113/bin/python3 /home/tyluan/Workspace/py_projects/MultiGarmentNetwork/dress_SMPL.py
Traceback (most recent call last):
  File "/home/tyluan/Workspace/py_projects/MultiGarmentNetwork/dress_SMPL.py", line 100, in <module>
    vt, ft = dp.get_vt_ft_hres()
  File "/media/sdf/tyluan/Workspace/py_projects/MultiGarmentNetwork/utils/smpl_paths.py", line 80, in get_vt_ft_hres
    vt, ft = SmplPaths.get_vt_ft()
  File "/media/sdf/tyluan/Workspace/py_projects/MultiGarmentNetwork/utils/smpl_paths.py", line 75, in get_vt_ft
    vt, ft = pkl.load(open(smpl_vt_ft_path))
TypeError: a bytes-like object is required, not 'str'

Now this is another typical error when using python3 for python2 pickle files...

So, I'm kind of stuck here. Can anyone help me?

**Comment by neonb88** [comment]
I'm very confused.  Are you using python3 or python2?

**Comment by neonb88** [comment]
@tyluann This has been covered extensively in various issues.  If you are loading pickles in python3, you may have to use `vt, ft = pkl.load(open(smpl_vt_ft_path, 'rb'),  encoding='latin1')`.  If you're using `python2`, maybe just use the 'binary' option like `vt, ft = pkl.load(open(smpl_vt_ft_path, 'rb'))`?  Hope that helps!  You can message me further if you have debugging questions

@bharat-b7 please close this issue so the rest of us can find issues that are still actually open.  Thanks
