### ISSUE TITLE
Mismatching dimension for beta

### ISSUE THREAD

**Issue by rupang818** [bharat-b7/MultiGarmentNetwork#48]
Hi,

I'm getting a mismatching dimension for "betas" - it's expecting 300, but only 10 is provided, it seems.

This is the un-pickle'd data for the dataset, 125611504192867:
```
{'gender': 'neutral', 'trans': array([ 0.01144017,  0.4054988 , -0.06529303]), 'pose': array([-1.30948492e-01, -3.29898631e-01, -9.84769401e-03,  1.59724660e-01,
        1.70258231e-01,  5.82928525e-02,  1.60398064e-01, -1.27556939e-01,
       -1.51460914e-01,  1.65358436e-01, -3.39140348e-02,  4.46965584e-02,
       -2.96297490e-02, -2.87718842e-01, -7.65404447e-02, -3.28753996e-02,
        2.70771298e-01,  9.86835024e-02, -2.09755920e-01,  4.78915284e-02,
        3.13358263e-02,  8.84452112e-02,  2.73602586e-01,  3.36349547e-01,
       -9.42140635e-03, -4.41118679e-01,  1.92312366e-01,  3.54518287e-01,
       -4.29150066e-02, -2.63765527e-03, -1.44436823e-01,  2.35914807e-01,
       -9.10371874e-01, -3.78722139e-01, -4.82762450e-02, -1.97441144e-01,
       -2.15493294e-01, -1.55975613e-01, -6.65946738e-02, -6.05518053e-02,
       -1.03392795e-01, -5.12201492e-01, -8.39527749e-02,  1.62397288e-01,
        5.70510420e-01,  1.37723341e-01,  3.94100762e-01,  2.24068899e-02,
        2.03482540e-01, -2.22209859e-01, -8.40104678e-01,  5.49966955e-01,
        2.87181538e-01,  6.93609469e-01,  4.54874611e-04, -2.86201205e-01,
       -1.70562943e-01, -2.19514235e-01,  3.43103307e-01,  5.36033078e-02,
        6.97114227e-01,  1.80469849e-01,  2.91453898e-01,  2.26552884e-01,
       -2.12755928e-01, -3.54147226e-01, -1.20267315e+00, -3.54949498e-01,
       -9.23388310e-01, -9.08903369e-01,  2.59012983e-01,  1.08350691e+00]), 'betas': array([-0.1835972 , -0.53515049,  0.37103371,  2.17440118,  0.34642864,
        0.42669621, -1.06463061, -0.10021483,  0.33851533, -0.06524306])}
```

Here's the error message that I'm getting:
```
Traceback (most recent call last):
  File "dress_SMPL.py", line 126, in <module>
    garment_org_body_unposed = load_smpl_from_file(join(path, 'registration.pkl'))
  File "dress_SMPL.py", line 32, in load_smpl_from_file
    smpl_h.betas[:] = dat['betas']
  File "/usr/local/lib/python3.6/dist-packages/chumpy/ch.py", line 512, in __setitem__
    data.__setitem__(key, value)
ValueError: could not broadcast input array from shape (10) into shape (300)
```

I also tried to hard-code the `smpl_h.betas[:]` to be shape (10), but that causes troubles in other calculations (I think later on when you dot-product it, it seems). What is "betas" and how would I match it to 300?

**Comment by bharat-b7** [comment]
The SMPL betas are PCA coefficients. You can use the first 10 betas as provided and set remaining 290 to zero.

**Comment by rupang818** [comment]
Thanks. That resolves it
