### ISSUE TITLE
Error when running python test_network.py

### ISSUE THREAD

**Issue by dev2021-ctrl** [bharat-b7/MultiGarmentNetwork#56]
**WARNING: failed to load librasterise.so; rasterisation functions will be unavailable:
 /usr/lib/x86_64-linux-gnu/libOpenGL.so.0: undefined symbol: _glapi_tls_Current
Using dirt renderer.
Traceback (most recent call last):
  File "test_network.py", line 14, in <module>
    from network.base_network import PoseShapeOffsetModel
  File "/home/ubuntu/MultiGarmentNetwork/network/base_network.py", line 17, in <module>
    from smpl.smpl_layer import SmplBody25Layer
  File "/home/ubuntu/MultiGarmentNetwork/smpl/smpl_layer.py", line 22
    def call(self, (pose, betas, trans)):
                   ^
SyntaxError: invalid syntax**

Please help @bharat-b7 . A  bit urgent

**Comment by bharat-b7** [comment]
What version of python are you using?

**Comment by dev2021-ctrl** [comment]
I am able to fix the above issue .I am using python 3.7 since I ported from 2to3 package.
Now when running  test_network.py there is no error  , but it is stuck with below message:
Complete logs

(dress) ubuntu@ip-172-31-7-48:~/MultiGarmentNetwork$ python test_network.py 
/home/ubuntu/anaconda3/envs/dress/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ubuntu/anaconda3/envs/dress/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ubuntu/anaconda3/envs/dress/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ubuntu/anaconda3/envs/dress/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ubuntu/anaconda3/envs/dress/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ubuntu/anaconda3/envs/dress/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using dirt renderer.
/home/ubuntu/anaconda3/envs/dress/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.decomposition.pca module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.decomposition. Anything that cannot be imported from sklearn.decomposition is now part of the private API.
  warnings.warn(message, FutureWarning)
/home/ubuntu/anaconda3/envs/dress/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator PCA from version 0.19.0 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

WARNING:tensorflow:From /home/ubuntu/MultiGarmentNetwork/smpl/batch_lbs.py:53: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Using latest checkpoint at saved_model/ckpt-26
Load test data
Get results before optimization
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/dress/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:642: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
