### ISSUE TITLE
make error when install mesh

### ISSUE THREAD

**Issue by yangbiaobiao500** [bharat-b7/MultiGarmentNetwork#7]
Excuse me, the mesh of the URL you gave only supports python3, but the environment you requested is py27. When I found the mesh running on py27, make had problems again.
Traceback (most recent call last):
  File "setup.py", line 266, in <module>
    ** additional_kwargs
  File "/home/ybb/study/MGN/mesh-master/temporary_test/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ybb/study/MGN/mesh-master/temporary_test/venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 192, in run
    self.run_command('build')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 127, in run
    return _build_ext.run(self)
  File "/home/ybb/study/MGN/mesh-master/temporary_test/venv/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 118, in build_extension
    return _build_ext.build_extension(self, ext)
  File "/home/ybb/study/MGN/mesh-master/temporary_test/venv/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 566, in compile
    depends, extra_postargs)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 331, in _setup_compile
    "'include_dirs' (if supplied) must be a list of strings")
TypeError: 'include_dirs' (if supplied) must be a list of strings
Makefile:48: recipe for target 'temporary_test/package_creation' failed
make: *** [temporary_test/package_creation] Error 1
I really need your help, thank you very much

**Comment by yangbiaobiao500** [comment]
python dress_SMPL.py 
Traceback (most recent call last):
  File "dress_SMPL.py", line 15, in <module>
    from utils.smpl_paths import SmplPaths
  File "/home/ybb/study/MGN/MultiGarmentNetwork-master/utils/smpl_paths.py", line 6, in <module>
    from psbody.smpl import load_model
ImportError: No module named smpl
Why is this? I need your help. I have n’t had any results in two weeks.

**Comment by bharat-b7** [comment]
> python dress_SMPL.py
> Traceback (most recent call last):
> File "dress_SMPL.py", line 15, in 
> from utils.smpl_paths import SmplPaths
> File "/home/ybb/study/MGN/MultiGarmentNetwork-master/utils/smpl_paths.py", line 6, in 
> from psbody.smpl import load_model
> ImportError: No module named smpl
> Why is this? I need your help. I have n’t had any results in two weeks.

The dependencies have been updated on 15/11. Pull latest version.

**Comment by yangbiaobiao500** [comment]
Thank you very much for your reply, I have been able to run it successfully, but there are still some problems in test_network.py. E.g:
RuntimeError: Error copying tensor to device: / job: localhost / replica: 0 / task: 0 / device: GPU: 1. / Job: localhost / replica: 0 / task: 0 / device: GPU: 1 unknown device.
Beyond that, I have some questions
1: When I run visualize_garments.py, this result surprised me
![Screenshot from 2019-11-28 10-14-32](https://user-images.githubusercontent.com/48718462/69771496-04ce9400-11c8-11ea-843b-41a59818d871.png)
As shown in the figure, the clothing on the left is a picture of a digital wardrobe, the human body model is smpl in the middle, and the image on the right is a picture after fitting. I want to ask if I can reconstruct the clothing that comes with the human body, such as outputting a few pictures. Can the surface clothes and mannequins of the target human body be reconstructed instead of the clothing in the digital wardrobe?
2: I don't know if your team wants to replace the human body model smpl with smpl-x to make the effect better. If I want to try to do this, I don't know if you have any good suggestions?
I sincerely admire the work of your team, it is really great, I look forward to your reply, thank you very much

**Comment by bharat-b7** [comment]
> Thank you very much for your reply, I have been able to run it successfully, but there are still some problems in test_network.py. E.g:
> RuntimeError: Error copying tensor to device: / job: localhost / replica: 0 / task: 0 / device: GPU: 1. / Job: localhost / replica: 0 / task: 0 / device: GPU: 1 unknown device.

To run the code on a single GPU comment out the lines containing ```with tf.device('gpu:x')```

> Beyond that, I have some questions
> 1: When I run visualize_garments.py, this result surprised me
> ![Screenshot from 2019-11-28 10-14-32](https://user-images.githubusercontent.com/48718462/69771496-04ce9400-11c8-11ea-843b-41a59818d871.png)
> As shown in the figure, the clothing on the left is a picture of a digital wardrobe, the human body model is smpl in the middle, and the image on the right is a picture after fitting. I want to ask if I can reconstruct the clothing that comes with the human body, such as outputting a few pictures. Can the surface clothes and mannequins of the target human body be reconstructed instead of the clothing in the digital wardrobe?

We haven't released the code to register garments and body from the scan yet.

> 2: I don't know if your team wants to replace the human body model smpl with smpl-x to make the effect better. If I want to try to do this, I don't know if you have any good suggestions?
> I sincerely admire the work of your team, it is really great, I look forward to your reply, thank you very much

Thanks a lot for your appreciation. Our retargeting is pretty general and can take any body mesh as input and it would be interesting to try out SMPL-X. If you want to re-train MGN with SMPL-X you would have to write code for registering scan against SMPL-X model

**Comment by yangbiaobiao500** [comment]
Thank you very much for your reply, so I want to know if this part of the code for registering clothing and body from the scan can be released? This is key to me and I look forward to your reply.
